/**
 * @duckd/adapters: one spec in, many host formats out.
 *
 * Every target below wants the same behaviour in a different file layout and a
 * different prompt dialect. Hand-maintaining five copies guarantees they drift,
 * and a drifted duck is a duck that hands over the answer in one editor and not
 * another. So: `docs/spec/socratic-protocol.md` is parsed once, and every artifact
 * is generated from it.
 *
 * Generated files carry a provenance header and are verified in CI. See the
 * `spec-drift` job in `.github/workflows/ci.yml`.
 */

export const ADAPTER_TARGETS = ['agents-md', 'claude-code', 'cursor', 'copilot', 'junie'] as const

export type AdapterTarget = (typeof ADAPTER_TARGETS)[number]

export interface GeneratedFile {
  /** Path relative to the output root. */
  readonly path: string
  readonly contents: string
}

export interface AdapterContext {
  /** Parsed contents of `docs/spec/socratic-protocol.md`. */
  readonly spec: SpecDocument
  /** Short revision string stamped into the provenance header. */
  readonly specRevision: string
}

export interface SpecDocument {
  readonly id: string
  readonly title: string
  readonly version: string
  readonly markdown: string
}

export interface Adapter {
  readonly target: AdapterTarget
  /** Where this host expects its files, relative to a project root. */
  readonly outputRoot: string
  render(context: AdapterContext): readonly GeneratedFile[]
}

/** Prepended to every generated artifact so nobody edits the output by mistake. */
export function provenanceHeader(target: AdapterTarget, specRevision: string): string {
  return [
    `Generated by @duckd/adapters (${target}) from docs/spec/socratic-protocol.md@${specRevision}.`,
    'Do not edit by hand. Change the spec and regenerate.',
  ].join('\n')
}

// TODO(spec): `parseSpec(markdown)` -> SpecDocument.
// TODO(targets): one Adapter per entry in ADAPTER_TARGETS.
// TODO(ci): `checkDrift(projectRoot)` -> non-zero exit when an artifact is stale.
